## TOML Configuration File
qa_question        = "This is the default question set in config.toml"
pdf_dir            = "./pdfs"
see_log_history    = false
transformer_type   = "sentence-transformers/all-MiniLM-L6-v2"
chromadb_dir       = "./chroma_db_nccn"
base_url           = "http://localhost:1234/v1"
api_key            = "not-needed"
chunk_size         = 1000
chunk_overlap      = 100
system_prompt      = "You are an intelligent assistant. You always provide well-reasoned answers that are both correct and helpful."
intro_prompt       = "Hello, introduce yourself to someone opening this program for the first time. Be concise."
template           = """Use the following pieces of context to answer the question at the end. \
If you don't know the answer, just say that you don't know, don't try to make up an answer. \
Use three sentences maximum. Keep the answer as concise as possible. Always say \
"thanks for asking!" at the end of the answer.  {context} \
Question: {question} \
Helpful Answer:"""

